### ISSUE TITLE
Custom template with new version?

### ISSUE THREAD

**Issue by kkranzo** [Automattic/facebook-instant-articles-wp#130]
With the previous version of the plugin (0.2), this worked great.

Does this no longer work? It doesn't seem to be working when I made the update.

```
add_filter( 'instant_articles_render_post_template', 'set_my_fbia_custom_template', 10, 3 );
function set_my_fbia_custom_template( $template, $post ) { 
	$template = dirname( __FILE__ ) . '/fbia/template.php'; 
	return $template; 
}
```

**Comment by diegoquinteiro** [comment]
Hi @kkranzo, 

Thanks for the question =)

You are right, that does not work anymore, v2 was a major change.

We're not using a template anymore, we're using the [Facebook Instant Articles SDK for PHP](facebook/facebook-instant-articles-sdk-php) transformer engine to generate a Instant Article Element that we then render on the output. Please read our [Quick Start](https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/docs/QuickStart.md) to understand how it works now.

You can intercept the InstantArticle element before it renders the output using the filter `instant_articles_transformed_element` and manipulate it there.

Can you share what kind of change do you wanna make on your output?

I can help you making them on the new version.

Thanks,
Diego

**Comment by kkranzo** [comment]
I was mainly using it to have greater control over the whole template (and in a more standard html/php manner rather than an SDK).

For example, I have several different post styles and I adjusted the output for Instant Articles accordingly within the template file.

I might just stick with my current version since I already have it all setup and it works great! I don't really need the simplicity of the new update (being able to adjust things with a UI, publish to Facebook page automatically, etc.).

**Comment by diegoquinteiro** [comment]
Hi @kkranzo,

Interesting point. Our SDK will ensure the markup generated is always correct according to our specs. 

I recommend doing the migration to v2+ at some point as 0.2 is not going to be supported/updated.

What kind of adjusts do you do for different post types? Can you give me some examples of the diferences between them?

We want it to be flexible enough to attend most use cases =)

**Comment by kkranzo** [comment]
@diegoquinteiro - I use ACF custom post fields for a lot of stuff on my site. So, some posts don't actually have any traditional "content". They use custom post fields like a gallery for example. So, if a post is a gallery, then within my custom template I grab the images from my custom field and output them in a Facebook Instant Articles friendly format. I use the same approach for some videos, etc.

And yeah, I hear you as far as the support/updates. But it seems like I might just stay with how it currently works and tweak as needed on my own if things change. Because with how different the new version is it seems like I would have to redo a lot of what I had already setup (since I had to do a lot of trial/error, customizations, and a lot of back and forth with Facebook for approvals).

-- Kyle

**Comment by demoive** [comment]
@kkranzo, from what you've described, the good news is that I believe your use case is supported in the new version. The *Transformer* that @diegoquinteiro mentioned above uses Rules to map any markup to accepted Instant Article *Elements* — and it, of course, is fully customizable :grinning:! Best case, you'll only have to customize the [Selector Rules](https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/docs/QuickStart.md#matching-selector) within the Settings of the WordPress plugin.

You're right that you might have to "redo" some work that you've already done to get the mapping, but your existing template might facilitate this work. I recommend re-considering upgrading because the gains are many — aside from the already mentioned continued support and parity with valid Instant Articles markup, the plugin now exposes setting options allowing you to customize various parts of the Instant Articles experience and we'll be adding more in the future.

**Comment by demoive** [comment]
@kkranzo before closing this out, I wanted to highlight two things:

1. Make sure to follow #150 since it relates to ACF as well. It's not the first time the same feature request has been made so it's being tracked as a possibility for the future.

2. In case you *do* upgrade to the latest version, we've recently extended our documentation with a section dedicated to help configuring the [Custom Transformer Rules](https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/docs/QuickStart.md#custom-transformer-rules) which would hopefully provide you with enough information for making any adjustments necessary to get the transformation to work in your environment.
