### ISSUE TITLE
Potential Bug?

### ISSUE THREAD

**Issue by samichamoun** [Automattic/facebook-instant-articles-wp#140]
I'm attempting to modify the HTML surrounding my HTML5 video player to be IA-compliant, using the "instant_articles_content" filter.

Prior to any manipulation, the embed code looks like this:

`<script src="//www.springboardplatform.com/js/overlay"></script><iframe id="crzy003_1621795" src="//cms.springboardplatform.com/embed_iframe/5365/video/1621795/crzy003/craziestsportsfights.com/10" width="600" height="400" frameborder="0" scrolling="no"></iframe>`

By using the toggle debug inf, I can see my filter is working, with the "Source Markup" showing this:

`<figure class="op-interactive"><iframe id="crzy003_1621795" src="http://cms.springboardplatform.com/embed_iframe/5365/video/1621795/crzy003/craziestsportsfights.com/10" width="600" height="400" frameborder="0" scrolling="no"></iframe></figure>`

However the transformed Markup has stripped it out, and the following error is being displayed:

> Invalid selector for fields (image.url). The node being transformed was <figure> in the context of InstantArticle within the Rule ImageRule with these properties: { image.url=StringGetter}

The iframe looks to be formatted correctly to me, so is this a bug?

**Comment by diegoquinteiro** [comment]
Hi @samichamoun,

Thanks for reporting. There is definitely a bug with our ImageRule settings and we'll look at it.

But our plugin does not expect IA-markup to be ready on the "source". It tries to get regular markup from WordPress and convert to IA-markup.

In order to accomplish what you're trying to do, you can simply enclose your custom player in `<div class="interactive"></div>` and it'll be transformed correctly (our Rules are set to detect `div.interactive` to create the right Interactive markup on the other end).

Let me know if that works for you!

**Comment by samichamoun** [comment]
Brilliant, that works thanks!

**Comment by samichamoun** [comment]
@diegoquinteiro apologies if I should have created a separate issue ticket for this, however it applies to the above. Any time I have a height set on my iframe, the plugin strips it out, making the video player look very short inside IA.

Any ideas?
