### ISSUE TITLE
Relative URLs in body result in FB error

### ISSUE THREAD

**Issue by schneidan** [Automattic/facebook-instant-articles-wp#163]
I link to internal pages using relative URLs in some old articles. These results in an error, even when they point to a page or post rather than an image:

`URL is Incomplete: The URL used for this media element is missing information. We have automatically filled in information for you. Please check that the URL is now correct and complete.`

The URL remains unchanged.

I am working on fixing along the way, since it's obviously not a best practice, but would it possible for the IA plugin to detect relative URLs and append something like `bloginfo( 'url' )` before them during the transform, or via a filter on `$content` before the transform? This may be a bridge too far...

**Comment by looselyCoupledGrip** [comment]
I am currently having a similar issue with my URL as well. 
Where as the canonical URL used in the articles are incomplete and do not specify the domain.
I am still new to all this so I don't know where should I go from here.

**Comment by looselyCoupledGrip** [comment]
I don't know if this will solve the issue or will answer the questions itself, but when I disabled the wp root relative URLS plugin it worked fine.

**Comment by schneidan** [comment]
Since that plugin's entire schtick is making your URLs relative when they can be, it would definitely cause this issue. The relative URL is the issue, because the IA plugin is just dropping in the relative paths into the output.

**Comment by philipjohn** [comment]
My gut feeling is that really this should be handled properly in the content by having absolute URLs. There are other effects to having relative URLs so while we could have the plugin handle it, it's still a sticking plaster for the root cause.

You could probably filter the content and find and fix those relative URLs, but it'd be better to do that as part of a 'fixer' that went through those articles and actually edited the content itself.
