### ISSUE TITLE
my site IMG not working

### ISSUE THREAD

**Issue by cycda120** [Automattic/facebook-instant-articles-wp#211]
hi Paulo:

I have a question.

my site IMG not working in Instant Articles for WP

MY img code:

[caption id="attachment_22922" align="alignnone" width="736"]
[IMG src="http://my.site.com/uploads/2016/04/test.jpg" alt="test" width="736" height="437" class="size-full wp-image-22922" /] test[/caption]

can you help me?

Thank you !

**Comment by everton-rosario** [comment]
@cycda120 Is this shortcode from a custom plugin?
Which one?

**Comment by abdusfauzi** [comment]
This issue still appear on latest version. Error:

`No rules defined for <div class="wp-caption alignnone"> in the context of InstantArticle`

**Comment by everton-rosario** [comment]
Hey @abdusfauzi 
please, can you share here more info about your transformation problem?

We need you to click in the link "**[Toggle debug information]**" in the "Instant Articles" meta-box and then copy and past the both editor's text: "**Source Markup**" and "**Transformed Markup**"

@abdusfauzi Please file another issue with your error and details, so we can help better. Your issue is not related to @cycda120 one.

@cycda120 Im closing this, if you still need some help, reopen please.
