### ISSUE TITLE
Button in wordpress = nothing in Instant article Feed

### ISSUE THREAD

**Issue by cusatxpress** [Automattic/facebook-instant-articles-wp#243]
Hello All,
## Problem
I do have a plugin that generates button code for wordpress posts. It was simple and gorgeous looking. But problem arises when the same is pulled to Facebook Instant articles feed, The button disappears. I have more than 200 articles with the same button so manually changing them wont do good.
I know Instant articles doesnt supports that code. 
## How i need the help ?
can you guys help me to transform it.?
the short code goes like this
`[dl url="LINK" title="Title" desc="description" type="pdf" align="center"]`

dl url : Button Link
titile : whats written above the button
Desc:
Type : Pdf
align: Center

I need the above short-code to look like this below.
`<a href="LINK" alt="description">Title</a>`

Thanks and Regards.
CX

**Comment by demoive** [comment]
Hi @cusatxpress. The most likely reason your link is being removed is because the transformer does not recognize the source markup of your button.

Some context: our plugin makes use of the [Facebook Instant Articles SDK for PHP](https://github.com/facebook/facebook-instant-articles-sdk-php) which contains a Transformer that does all the heavy lifting of converting general markup into valid Instant Articles markup. The way that it knows how to transform source elements into the valid Instant Articles markup is by a set of rules which defines the mapping of how to parse the content of the post/page. Our plugin contains Rules which have been pre-defined to satisfy the most common WordPress source markup, but the markup for your button may not be covered by the packaged ruleset.

We've recently extended our documentation with a section dedicated to help configuring the [Custom Transformer Rules](https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/docs/QuickStart.md#custom-transformer-rules). Hopefully it provides enough information for you to define or make any adjustments necessary to get the transformation to work in your environment.

In order to have it logged here on this issue, can you share the markup that is produced by your shortcode? Also, out of curiosity, what is this shortcode you are using? Is it the [Download Button Shortcode](https://wordpress.org/plugins/download-button-shortcode/)?

**Comment by cusatxpress** [comment]
yes its a Download button shortcode.

Plugin URL : http://blog.ppfeufer.de/wordpress-button-fuer-downloads-erzeugen/

and CSS

`@CHARSET "UTF-8";
/* Download Buttons + Comment Submit Button */
.dwnld-button-shortcode {
/* 	margin: 10px; */
	border-radius: 5px;
	border: 1px solid #808080;
	padding: 2px;
	-webkit-box-shadow: 0 0 3px 0 rgba(125,125,125,0.5), inset 0 0 0 2px #ccc;
	-moz-box-shadow: 0 0 3px 0 rgba(125,125,125,0.5), inset 0 0 0 2px #ccc;
	box-shadow: 0 0 3px 0 rgba(125,125,125,0.5), inset 0 0 0 2px #ddd;
	display: inline-block;
}
.dwnld-button-shortcode:hover {
	-webkit-box-shadow: inset 0 0 0 2px #ddd;
	-moz-box-shadow: inset 0 0 0 2px #ddd;
	-ms-box-shadow: inset 0 0 0 2px #ddd;
	box-shadow: inset 0 0 0 2px #ddd;
}
.dwnld-button-shortcode:active {
	border: 1px solid #b3b3b3;
}
.dwnld-button-shortcode a {
	display: block;
	padding: 0 0 0 50px;
	background: #ddd;
	background: -webkit-linear-gradient(top, #ececec, #ddd);
	background: -moz-linear-gradient(top, #ececec, #ddd);
	background: -o-linear-gradient(top, #ececec, #ddd);
	background: -ms-linear-gradient(top, #ececec, #ddd);
	background: linear-gradient(top, #ececec, #ddd);
	filterrogidXImageTransform.Microsoft.gradient(GradientType, startColorstr='#ececec', endColorstr='#dddddd'); /* IE 7 */ 
	-ms-filterrogidXImageTransform.Microsoft.gradient(GradientType, startColorstr='#ececec', endColorstr='#dddddd'); /* IE 8 */
	border-radius: 4px;
}
.dwnld-button-shortcode a, .dwnld-button-shortcode a:hover, .dwnld-button-shortcode a:active {
	text-decoration:none;
	color: #373737;
}
.dwnld-button-shortcode > a > span {
	padding: 15px;
	border-radius: 0 3px 3px 0;
	display: block;
	font-size: 18px;
	line-height:100%;
	background: #fff;
	background: -webkit-linear-gradient(top , #fff, #f0f0f0);
	background: -moz-linear-gradient(top , #fff, #f0f0f0);
	background: -o-linear-gradient(top , #fff, #f0f0f0);
	background: -ms-linear-gradient(top , #fff, #f0f0f0);
	background: linear-gradient(top , #fff, #f0f0f0);
	filterrogidXImageTransform.Microsoft.gradient(GradientType, startColorstr='#ffffff', endColorstr='#f0f0f0'); /* IE 7 */ 
	-ms-filterrogidXImageTransform.Microsoft.gradient(GradientType, startColorstr='#ffffff', endColorstr='#f0f0f0'); /* IE 8 */
}
.dwnld-button-shortcode a span em {
	font-size: 14px;
}
.button-download {
	width: 100%;
	max-width: 280px;
	position: relative;
	display: block;
	background: #ddd;
	background: -webkit-linear-gradient(top, #ececec, #ddd);
	background: -moz-linear-gradient(top, #ececec, #ddd);
	background: -o-linear-gradient(top, #ececec, #ddd);
	background: -ms-linear-gradient(top, #ececec, #ddd);
	background: linear-gradient(top, #ececec, #ddd);
	filterrogidXImageTransform.Microsoft.gradient(GradientType, startColorstr='#ececec', endColorstr='#dddddd'); /* IE 7 */ 
	-ms-filterrogidXImageTransform.Microsoft.gradient(GradientType, startColorstr='#ececec', endColorstr='#dddddd'); /* IE 8 */
}
.button-download a { 
	padding-left: 75px;
	background:url(../img/button-download.png) 20px 45% no-repeat;
}
.button-download a.type-pdf {background:url(../img/button-pdf.png) 18px 45% no-repeat;}
.button-download a.type-link {background:url(../img/button-link.png) 20px 45% no-repeat;}
.button-download a.type-doc {background:url(../img/button-doc.png) 20px 45% no-repeat;}
.button-download a.type-image {background:url(../img/button-image.png) 20px 45% no-repeat;}
.button-download a.type-archive {background:url(../img/button-archive.png) 20px 45% no-repeat;}
.button-download a.type-audio {background:url(../img/button-audio.png) 20px 45% no-repeat;}
.button-download a.type-video {background:url(../img/button-video.png) 20px 45% no-repeat;}`

**Comment by demoive** [comment]
@cusatxpress the link you provided leads to a "This site cannot be reached" message (ERR_NAME_NOT_RESOLVED). Can you double check?

**Comment by everton-rosario** [comment]
@cusatxpress Do you still have this issue?

Ill close it, feel free to add more details so we can help you solve this.

Thanks for using Instant Articles.
