### ISSUE TITLE
Google analytic is not registering my traffic that is coming from fb instant articles

### ISSUE THREAD

**Issue by amjad-eremnews** [Automattic/facebook-instant-articles-wp#321]
Google analytic is not registering traffic coming from fb instant articles. i hope that I have configured it properly.
Please check the screenshot of my settings and confirm me if these are fine. **Note**: I didn't enclosed analytic code in iframe tags.

![screenshot from 2016-06-15 12 33 42](https://cloud.githubusercontent.com/assets/19947761/16073272/341b4032-32f6-11e6-8426-bf71dc2a2e7f.png)

**Comment by CarsonLee27** [comment]
You may try by using their recommended plugin - https://www.monsterinsights.com/welcome-to-monsterinsights/ to double check with the issue. 

I kind of having the same issues. 
Just GA does register but in less I believe and it show (notset) in the GA for the article came from FB instant article.

**Comment by amjad-eremnews** [comment]
I am unable to fixed the issue, it is still not registering the fb instant article traffic.

**Comment by GOT1878** [comment]
I also have this problem...

**Comment by amjad-eremnews** [comment]
I have fixed it by disabling https in the analytics code. my code is now as under:

`<script type="text/javascript">
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','__gaTracker');

	__gaTracker('create', 'UA-xxxxxxxx-x', 'auto');
	__gaTracker('set', 'forceSSL', false);
	__gaTracker('send','pageview', {title: 'POST TITLE'});
</script>`

or 

you can also try with enabling https on your site.

**Comment by GOT1878** [comment]
Thank you very much amjad, I really appreciate you taking the time to feedback and assist. So is your full code;

<iframe>
<script>
 (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','__gaTracker');

__gaTracker('create', 'UA-xxxxxxx', 'auto');
__gaTracker('set', 'forceSSL', false);
__gaTracker('send','pageview', {title: 'POST TITLE'});

</script>
  </iframe>

**Comment by GOT1878** [comment]
Appreciate a label of 'bug/needs investigation' was applied 20 days ago, but we've had two updates since and the problem persists. 

Any chance any kind soul out there can assist?

**Comment by everton-rosario** [comment]
@GOT1878 have you removed the <iframe> tags?

It is not needed, because the plugin will add it automatically.

If you need more assistance @GOT1878, please add few more info here.

We need you to click in the link "**[Toggle debug information]**" in the "Instant Articles" meta-box and then copy and past the both editor's text: "**Source Markup**" and "**Transformed Markup**"

Thanks for using Instant Articles.

**Comment by CarsonLee27** [comment]
@GOT1878 

May I know how can you register this post title with this line? 
__gaTracker('send','pageview', {title: 'POST TITLE'});

I realise GA direct showing POST TITLE xD.

**Comment by everton-rosario** [comment]
@GOT1878 you can remove the content in jason, so google analytics will grab it from the document title.

Try doing it like this:
`__gaTracker('send','pageview');`

**Comment by CarsonLee27** [comment]
@everton-rosario I have tried the default (without the title: 'POST TITLE'). Unfortunately, the GA show not set for the title.

**Comment by ramseymohsen** [comment]
I'm having trouble with this issue to. Were you able to fix this? Here is the code I'm putting in:

`<script>
 (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','__gaTracker');

__gaTracker('create', 'UA-XXXXXXX', 'auto');
__gaTracker('set', 'campaignName', 'FB-Instant');
__gaTracker('send','pageview', {title: 'POST TITLE'});
</script>

`

**Comment by everton-rosario** [comment]
@ramseymohsen sending `{title: 'POST TITLE'} ` will make all articles to have the same Title on your GA report.

You will need to leave it empty (removing it from this config generator) and rely on the path structure, or you can do an customization where every single page overwrite this content on the tracking code with the proper "POST TITLE".

Since this is specific to people not relying on this we still didn't get the time to create this customization by configuration.

If any of you guys can share the code, we can work together in a PullRequest and have this featured shared to community.

Thanks.

**Comment by ryanissamson** [comment]
> You will need to leave it empty (removing it from this config generator) and rely on the path structure, or you can do an customization where every single page overwrite this content on the tracking code with the proper "POST TITLE".

Could you expound a bit more on that please? Thanks!

**Comment by Asif2BD** [comment]
And this was never resolved? How come? What kind of development is going on here?

**Comment by jeremyclarke** [comment]
What a mess! It's Facebook's fault for not passing the title by default, WTF they are thinking with that I will never know. Only sensible explanation is it's warfare on Google Analytics or something, totally strange!

And why don't they mention that title will be saved as "(not set)" on this page??? https://developers.facebook.com/docs/instant-articles/analytics

They even give a very weak example of how to use their API to set it, but don't mention why (i.e. BECAUSE THEY DON'T DO IT!). 

Totally unnacceptable. I bet almost every user is eventually shocked to find none of their iA hits have title, and that, ironically, the way to identify iA traffic in Google Analytics is to find the broken hits with no title set.

**Comment by jeremyclarke** [comment]
Here's a bunch of people desperately trying to overcome the outrageous lack of code and documentation support for having titles save in Google Analytics: http://stackoverflow.com/questions/36310439/how-to-track-content-statistics-for-facebook-instant-articles-with-google-analyt

**Comment by jeremyclarke** [comment]
Just added an answer to that Stack Overflow question where I give an example Universal Analytics snippet that solves the title not set problem as well as adding source and medium tags: 

http://stackoverflow.com/questions/36310439/how-to-track-content-statistics-for-facebook-instant-articles-with-google-analyt/42587025#42587025

IMHO something about how to add the title value with ` ga('set', 'title', ia_document.title);` should probably be added to the docs for this plugin anywhere that GA code is mentioned, since 100% of users will want this to work properly and Facebook isn't doing a good job at all of communicating the fact that titles won't be visible in GA.

**Comment by athinorama** [comment]
I Finally Manage to get things working
my exact code is

<figure class="op-tracker">
                <iframe>
                    <script>
                        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
						ga('create', 'UA-XXXXXXXX-1', 'auto');
                        ga('require', 'displayfeatures');
                        ga('set', 'campaignSource', 'Facebook');
                        ga('set', 'campaignMedium', 'Social Instant Article');
                        ga('set', 'title', 'bla bla bla bla bla bla bla bla bla ');
                        ga('send', 'pageview');
                    </script>
                </iframe>
            </figure>

The only thing i've done is to move this code snippet from the 
<footer> section where i'd placed it in the first place
to  just under <article>
and the everything started to flow!

**Comment by MrSunshyne** [comment]
I recently realised that the "Medium" field in GA that used to show "Instant Article" has completely disappeared. Under source/medium I only see 'facebook / referral' now. 
This is a huge issue as i cannot distinguish my FBIA traffic from regular traffic anymore. 
Anybody else ran into this issue ?

**Comment by everton-rosario** [comment]
@MrSunshyne you can add any personal tags to your GA snippet that goes into only your Instant Articles making it possible for you to track as you wish.

Just like the above script that @maxinnos commented:
```
<script>
(function (i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function () {(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-   analytics.com/analytics.js','ga');
ga('create', 'UA-XXXXXX-1', 'auto');
ga('require', 'displayfeatures');
ga('set', 'campaignSource', 'Facebook'); 
ga('set', 'campaignMedium', 'Social Instant Article');   /// This is the line setting a flag so you can query on GA.
ga('set', 'title', ia_document.title); 
ga('send', 'pageview');
</script>
```

**Comment by Asif2BD** [comment]
Its unfortunate its still an on-going problem.

This is what works for me, just put this way in "Enable custom embed code" - 

`<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-XXXXXXXX-XX', 'auto');
  ga('require', 'displayfeatures');
  ga('set', 'campaignSource', 'Facebook');
  ga('set', 'campaignMedium', 'Instant Article');
  ga('set', 'title', ia_document.title);
  ga('send', 'pageview');
</script>`

**Comment by everton-rosario** [comment]
What do you mean by "Enable custom embed code"?

**Comment by reddybang** [comment]
@athinorama Thanks a lot working perfect....
