### ISSUE TITLE
Support for IA footers?

### ISSUE THREAD

**Issue by samichamoun** [Automattic/facebook-instant-articles-wp#335]
Obviously it would be great if the plugin had the ability to configure IA footers, however until this is made available, could someone please confirm what would be the best way for us to use these within an article?

**Comment by demoive** [comment]
Hi @samichamoun. Here are some options:

- You could add the [footer markup](https://developers.facebook.com/docs/instant-articles/reference/footer) to the bottom of each article. For example:

  ```html
  <footer>
    <aside>My footer</aside>
  <footer>
  ```

- Optionally, if you want that footer to *only* appear within Instant Articles (and not on your regular web) you could hide it with a CSS styling

  ```css
  footer {
    display: none;
  }
  ```

- Furthermore, if you have access to your WordPress template, you could add the markup there in order to avoid having to add the same footer on every article.

The official feature request is logged in #261. I've tagged it with the next milestone to bring attention to  is complete
