### ISSUE TITLE
Allow interactivity to be turned on/off for images

### ISSUE THREAD

**Issue by kkranzo** [Automattic/facebook-instant-articles-wp#36]
Is there a way to make it so the below interactivity would be added to images within the content?

```
<figure data-feedback="fb:likes, fb:comments">
</figure>
```

**Comment by dleatherman** [comment]
+1

**Comment by cassler** [comment]
+1

**Comment by seeReadCode** [comment]
+1

**Comment by riccarbi** [comment]
+1

**Comment by harush** [comment]
this rule works for me:
```
{
        "class": "ImageRule",
        "selector" : "figure",
        "properties" : {
            "image.url" : {
                "type" : "string",
                "selector" : "img",
                "attribute": "src"
            },
            "image.comments": {
                "type": "exists",
                "selector": "figure",
                "attribute" : ""
            },
            "image.like": {
                "type": "exists",
                "selector": "figure",
                "attribute" : ""
            }
        }
    } 
```

**Comment by abdusfauzi** [comment]
How do we do this? The above rules didn't work for me.

**Comment by everton-rosario** [comment]
We will work on this issue soon @abdusfauzi so we can have a default config setup on the Rules.json.

**Comment by everton-rosario** [comment]
@kkranzo @dleatherman @cassler @seeReadCode @riccarbi @harush @abdusfauzi 
1. Do you guys prefer this setup into the transformation rule, setting as default on the transformation rules? or,
2. Do you think it is better to have this as a general plugin config with a switcher on/off to all images?

**Comment by seeReadCode** [comment]
I would think 2 but it's a been a while since I used this. And as per the lead question in this issue, I can't remember if Facebook's context selectors respect/use data attributes.

**Comment by demoive** [comment]
The default option for whether asset-level feedback is enabled/disabled is a setting within a Facebook Page's configuration.

<img width="1019" alt="feedback-settings" src="https://cloud.githubusercontent.com/assets/472288/24244609/91d08766-0fb7-11e7-8fcb-54fcea30a0ec.png">

The ability to specify this setting on individual media elements is intended to be an override for the global setting mentioned above. So I almost feel like the two options added in #617 should be on a article-level, rather than a global setting which applies to all articles.
