### ISSUE TITLE
Not able to click on Get started and advance settings after installing the plugin of "instant articles for WP version 3.1.2" on wordpress

### ISSUE THREAD

**Issue by Anuj2812** [Automattic/facebook-instant-articles-wp#441]
The plugin (Instant articles for WP) version 3.1.2 is installed but we are unable to click on the buttons “Get started” and “Advanced Settings”. its not moving after the wizard.

**Comment by yeopmi** [comment]
i'm also having same problem

**Comment by demoive** [comment]
Thanks for reporting this @Anuj2812 and @yeopmi. I've been able to reproduce this if I disable Javascript in my browser, so I suspect that is what is happening in your case.

Can you confirm if you have JS intentionally disabled? Or perhaps a JS error has occurred by some other plugin and therefore preventing JS from executing properly within the admin? You can verify this by opening the Console, if you're using Chrome, by clicking: Menu > More Tools > Developer Tools > Console.

If you are able to get JS enabled and properly executing in your browser, I suspect it will resolve the problem locally and you can move on with the Wizard setup flow before this issue is addressed.

**Comment by demoive** [comment]
@Anuj2812 @yeopmi it just occurred to me that subsequent steps of the wizard setup flow depend on Javascript in order to work properly — so it's in fact necessary to get JS enabled and executing properly to use the settings of this plugin.

Is this something you are able to do?

**Comment by thanwaisoe** [comment]
same problem..
already check the JS issue.
clean error.

(Instant articles for WP) version 3.2
WordPress 4.6.1

**Comment by demoive** [comment]
@thanwaisoe, can you clarify what you mean by "clean error"?

**Comment by thanwaisoe** [comment]
I mean no JS error.
just now ok..
I changed the plugin folder name from 'fb-instant-articles' to 'facebook-instant-articles-wp'.

Thanks you.

**Comment by demoive** [comment]
@thanwaisoe, do you recall if you installed the plugin through the WordPress admin, or manually by downloading the zip file from GitHub?

**Comment by thanwaisoe** [comment]
I just installed the plugin from WP admin panel.

**Comment by demoive** [comment]
The plugin requires JavaScript to work properly so it needs to be enabled and working without errors.
