### ISSUE TITLE
Add support for posts using "more" tag

### ISSUE THREAD

**Issue by jashsayani** [Automattic/facebook-instant-articles-wp#451]
Add support for posts using "more" tag. The plugin should go through the full article for every article using the "more" tag. Most blogs use this and not supporting this tag does not make the plugin very useful.

**Comment by everton-rosario** [comment]
@jashsayani Im using the very same feature that comes within Wordpress vanila installation.
The "More" button should be removed, since in Instant Articles policy, you can't hide any content from the reader.

So in an example like this:
```
Paragraph one with some amazing text that incites me to keep reading...
------ More Tag -------
Here comes my hidden text that any reader will need to click "read more" to keep reading.
```

This is being transformed into a valid markup, which will be:
```
...
<article>
...
    <p>Paragraph one with some amazing text that incites me to keep reading...</p>
    <p>Here comes my hidden text that any reader will need to click "read more" to keep reading.</p>
...
</article>
```


Can you provide more info, I assume this is the correct behavior for the "more" button, so we shouldn't change anything. Let me know if you have any different Idea. Feel free to reopen.
