### ISSUE TITLE
Plugin version 3.1.2 has error (wizard-template.php on line 101)

### ISSUE THREAD

**Issue by jashsayani** [Automattic/facebook-instant-articles-wp#452]
I just updated the plugin to 3.1.2 (also deleted and installed the plugin), and I see the following error when I go to "Instant Articles" in Dashboard:

```
Fatal error: Can't use function return value in write context in /home/myusername/public_html/wp-content/plugins/fb-instant-articles/wizard/templates/wizard-template.php on line 101
```

**Comment by demoive** [comment]
Hi @jashsayani. Thanks for your feedback.

I wasn't able to reproduce the issue as you described it. Could you provide some more information about your environment and/or screenshots of the problem? For starters:

1. What "state" of the Setup Wizard are you in? For example, have you gone through all four initial setup steps?
2. What's your Wordpress version? The current latest is v4.6.1 which can be seen on the bottom right corner of any admin page of your Wordpress.

**Comment by arbalister** [comment]
I get the same error.  This is a pre-exiting install, I've had it since FB announced instant articles.  I've used it successfully in the past.

Sometime since the last update, I get a message at the top of the WP admin page thanking me for installing Instant Articles, click here to activate... and then I get the error.  I also get the error just clicking Instant Articles on the left menu.

Error is:

Fatal error: Can't use function return value in write context in /home/redacted/public_html/wp/wp-content/plugins/fb-instant-articles/wizard/templates/wizard-template.php on line 101

**Comment by demoive** [comment]
Tracking the same issue reported on the WP community forum: https://wordpress.org/support/topic/very-bad-experience-2/

**Comment by demoive** [comment]
@jashsayani @arbalister if you're able to check the PHP version your server uses, I suspect it's something less than v5.5? Can you confirm?

I've traced the cause of this issue to be the use of the `empty()` function on PHP versions prior to v5.5. See more here: http://php.net/manual/en/function.empty.php and http://stackoverflow.com/questions/1075534/cant-use-method-return-value-in-write-context

I've submitted PR #464 to fix this issue and we're working to get a patch out before the next official release.

**Comment by arbalister** [comment]
Confirmed this much, my php is v5.4

**Comment by arbalister** [comment]
I just checked, you are correct, for me, at least.  PHP v5.4

**Comment by arbalister** [comment]
And... changing versions to 5.5, the error is gone.  So... that seems to be it.

**Comment by demoive** [comment]
@jashsayani @arbalister Just dropping a note that v3.1.3 is out and available for download. Upgrading to this latest version should resolve the problem!

**Comment by jashsayani** [comment]
Thanks for the update!
