### ISSUE TITLE
Empty page on plugin settings page

### ISSUE THREAD

**Issue by akashsrivastavaseo** [Automattic/facebook-instant-articles-wp#471]
# Steps required to reproduce the problem

1. Install plugin 
2. Activate plugin 
3. The link to all plugins page and this plugin setting page are blank.  In URL these are blank : 
/wp-admin/plugins.php
/wp-admin/admin.php?page=instant-articles-wizard

# Expected Result

* To see a wizard or settings screen of the plugin and all plugins page 

# Actual Result

* Pages are empty

---

** Version Info **

* Plugin version: 3.1.3
* WordPress version:  4.6.1

**Comment by everton-rosario** [comment]
@akashsrivastavaseo Can you paste here the stack trace you have for this case?

The logs of your PHP server contains the stack traces.

Check if any of these cases have the correct log path for your webserver: [http://unix.stackexchange.com/questions/38978/where-are-apache-file-access-logs-stored](url)

just copy and paste it here, so we can treat this better.

Thanks.

**Comment by gil2** [comment]
Hi @everton-rosario , I'm having the same problem. I'm also using WP 4.6.1 and Instant Articles 3.1.3.

Here's the error log (with site name blacked out)

[Wed Sep 21 12:08:23 2016] [error] [client 127.0.0.1] PHP Fatal error:  Uncaught exception 'Facebook\\Exceptions\\FacebookAuthenticationException' with message 'Error validating access token: The session has been invalidated because the user has changed the password.' in /var/www/vhosts/--/wp-content/plugins/fb-instant-articles/vendor/facebook/php-sdk-v4/src/Facebook/Exceptions/FacebookResponseException.php:89\nStack trace:\n#0 /var/www/vhosts/--/wp-content/plugins/fb-instant-articles/vendor/facebook/php-sdk-v4/src/Facebook/FacebookResponse.php(210): Facebook\\Exceptions\\FacebookResponseException::create(Object(Facebook\\FacebookResponse))\n#1 /var/www/--/wp-content/plugins/fb-instant-articles/vendor/facebook/php-sdk-v4/src/Facebook/FacebookResponse.php(255): Facebook\\FacebookResponse->makeException()\n#2 /var/www/--/wp-content/plugins/fb-instant-articles/vendor/facebook/php-sdk-v4/src/Facebook/Fa in /var/www/--/wp-content/plugins/fb-instant-articles/vendor/facebook/php-sdk-v4/src/Facebook/Exceptions/FacebookResponseException.php on line 89, referer: http://--/wp-admin/

Thanks!

**Comment by mokipedia** [comment]
we seem to have a similar problem, though we haven't found anything in the logs yet.
looking at your error log it looks that the auth process is not working which kills the settings page ..?

**Comment by praveenzoho** [comment]
similar issue for me as well.

This is the PHP error frm my site error log

> [Thu Sep 22 08:21:07 2016] [error] [client 188.40.46.135] PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, function 'sfw_load_pwd' not found or invalid function name in /home/site/mysite/wordpress/wp-includes/plugin.php on line 524
[Thu Sep 22 08:21:07 2016] [error] [client 182.74.243.43] PHP Fatal error:  Uncaught exception 'Facebook\\Exceptions\\FacebookAuthenticationException' with message 'This IP address is not on the Server IP whitelist' in /home/site/mysite/wordpress/wp-content/plugins/fb-instant-articles/vendor/facebook/php-sdk-v4/src/Facebook/Exceptions/FacebookResponseException.php:106\nStack trace:\n#0 /home/site/mysite/wordpress/wp-content/plugins/fb-instant-articles/vendor/facebook/php-sdk-v4/src/Facebook/FacebookResponse.php(210): Facebook\\Exceptions\\FacebookResponseException::create(Object(Facebook\\FacebookResponse))\n#1 /home/site/mysite/wordpress/wp-content/plugins/fb-instant-articles/vendor/facebook/php-sdk-v4/src/Facebook/FacebookResponse.php(255): Facebook\\FacebookResponse->makeException()\n#2 /home/site/mysite/wordpress/wp-content/plugins/fb-instant-articles/vendor/facebook/php-sdk-v4/src/Facebook/FacebookResponse.php(82): Facebook\\FacebookResponse->decodeBody()\n#3 /home/site/mysite/wordpress/wp-content/plugins/fb-instant-articles/vendor/facebook/php-sdk-v4/src/Faceb in /home/site/mysite/wordpress/wp-content/plugins/fb-instant-articles/vendor/facebook/php-sdk-v4/src/Facebook/Exceptions/FacebookResponseException.php on line 106, referer: https://blogs.mysite.com/wp-admin/edit.php
[Thu Sep 22 08:21:15 2016] [error] [client 188.40.46.135] PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, function 'sfw_load_pwd' not found or invalid function name in /home/site/mysite/wordpress/wp-includes/plugin.php on line 524

**Comment by everton-rosario** [comment]
@gil2 thanks for sharing your logtrace. Im checking this and how we can provide an token revalidation to login again if the token got expired.

Also thanks to @praveenzoho @mokipedia and @akashsrivastavaseo for flagging this.

I'll let you guys know about my progress on this.

**Comment by praveenzoho** [comment]
I am able to import my topics to FB instant articles without any plugin support.

**Comment by demoive** [comment]
@gil2 Just wanted to let you know that the issue you're having with "changed password" will be tracked here: #456. They may very will be solved by the same problem that @everton-rosario is focussing on here with this "blank page" issue, but I wanted to inform you anyway.

**Comment by gil2** [comment]
Thanks @demoive

**Comment by everton-rosario** [comment]
Hey just a heads up that I have this PR #481 that should fix all reported issues on this thread.

Sorry for the long wait. We will do the best we can to release this ASAP.

**Comment by demoive** [comment]
@akashsrivastavaseo @gil2 @mokipedia v3.2 was been released earlier this week which contains the fix. Can you confirm that after upgrading, you no longer experience the issue?

**Comment by gil2** [comment]
I apologize for the delay, I was pulled off to other projects. We upgraded, but we're still having the problem. 

[Mon Nov 07 10:17:04 2016] [error] [client 127.0.0.1] PHP Fatal error:  Uncaught exception 'Facebook\\Exceptions\\FacebookAuthenticationException' with message 'Error validating access token: The session has been invalidated because the user has changed the password.' in /var/www/vhosts/12tribefilmstv2.com/httpdocs/--/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Exceptions/FacebookResponseException.php:89\nStack trace:\n#0 /var/www/vhosts/12tribefilmstv2.com/httpdocs/--/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(210): Facebook\\Exceptions\\FacebookResponseException::create(Object(Facebook\\FacebookResponse))\n#1 /var/www/vhosts/12tribefilmstv2.com/httpdocs/--/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(255): Facebook\\FacebookResponse->makeException()\n#2 /var/www/vhosts/12tribefilmstv2.com/httpdocs/--/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Facebo in /var/www/vhosts/12tribefilmstv2.com/httpdocs/--/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Exceptions/FacebookResponseException.php on line 89, referer: http://www.--.com/wp-admin/update-core.php

Thanks
Gil

**Comment by everton-rosario** [comment]
@gil2 this is being centralized into this: #565 
Try the troubleshooting.

The login + app ID will be deprecated.
