### ISSUE TITLE
how to setup a rule to include a hosted video defined like  <script src="..." async></script>

### ISSUE THREAD

**Issue by fventu** [Automattic/facebook-instant-articles-wp#476]
Hi, in my desktop version the html code to show my embedded videos is something like this:
`<script src="https://player.mysite.com/eplayer.js#47e9db5b36e29d.196fz0zppum9417$videoid=18fv9y98thab31" async></script>`

In the transformed markup this tag is not shown at all. How can I set a rule to include this? (FB is preventing me the subscription because of this)
*\* Version Info **
- Plugin version: 3.1.3
- WordPress version: 4.6.1
- PHP version:

**Comment by mskogly** [comment]
I've been having a hard time trying to figure out how to work with the custom transform rules, but I now have this code

<div class="nrk-video" data-nrk-id="263723"></div><script src="http://www.nrk.no/serum/latest/js/video_embed.js"></script>

I added this custom transform rule
{
        "class": "PassThroughRule",
        "selector": ".nrk-video+p script"
      }
and that seems to work. It basically says to pick the script following a p (because wordpress adds that automatically for some reason) following an element with the class .nrk-video. 

In your case this might work
{
        "class": "PassThroughRule",
        "selector": "p script"
      }

Or try without the p

{
        "class": "PassThroughRule",
        "selector": "script"
      }

**Comment by fventu** [comment]
Thank you very much @mskogly I'll try and let you know. Regards

**Comment by diegoquinteiro** [comment]
I'd actually use an InteractiveRule:

```
{
    "rules":
    [{
        "class": "InteractiveRule",
        "selector" : "script[async]",
        "properties" : {
            "interactive.iframe" : {
                "type" : "element",
                "selector" : "script"
            },
        }
    }]
}
```

Please re-open if that doesn't work for you!
