### ISSUE TITLE
Elements not being converted to figures when in "a" and "paragraph" tags

### ISSUE THREAD

**Issue by kkranzo** [Automattic/facebook-instant-articles-wp#53]
I noticed that images and iframes/embeds are not being wrapped in figure tags if they are within "paragraph" tags or "a" tags. I had some situations where images were within a paragraph tag and then had an "a" tag around it as well since the image was linked.

Can you make it so elements have all surrounding tags removed?

Below are a couple of examples of elements that were not sanitized properly.

`<p><iframe src="https://www.youtube.com/embed/1234567" width="620" height="349" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>`

`<p><img class="alignnone wp-image-22167 size-full" src="http://www.domain.com/pathtoimage.jpg" width="500" height="280"></p>`

**Comment by kkranzo** [comment]
I just noticed a twitter embed wasn't sanitized properly either since it was within "p" tags:

**Comment by kkranzo** [comment]
Should the posts be filtered prior to wpautop being applied by the plugin?

**Comment by kkranzo** [comment]
Ah, okay. So it most be working for some instances because those certain Youtube videos were inserted using Oembed then rather than iframe. It seems like wrapping all iframes as interactive would work. That would be a great addition.

**Comment by kkranzo** [comment]
And to that point, nothing embed as an iframe or javascript embed (like Twitter) will work correctly, right?

They need to be added as an Oembed, correct?

**Comment by kkranzo** [comment]
It would be great to handle wrapping embeds (iframes, javascript embeds, etc.) in `<figure class="op-interactive">` tags.

**Comment by everton-rosario** [comment]
This should be fixed on master.
Can you double check it, please?

**Comment by kkranzo** [comment]
@everton-rosario - Are you referring to the iframes, etc. now being wrapped in op-interactive tags?

**Comment by diegoquinteiro** [comment]
@kkranzo yes, that should be working now. We're handling:

- Images/iframes under <p>.
- Images under <a>.

**Comment by kkranzo** [comment]
@diegoquinteiro - I updated the plugin, however it broke some things with my current setup so I reverted back.

I currently use my own template and utilize the function below in my functions.php file, but it looks like that no longer works.

add_filter( 'instant_articles_render_post_template', 'set_my_fbia_custom_template', 10, 3 );
function set_my_fbia_custom_template( $template, $post ) { 
	$template = dirname( __FILE__ ) . '/fbia/template.php'; 
	return $template; 
}

Is that no longer compatible with the new update?

Thanks,

-- Kyle

**Comment by kkranzo** [comment]
The current version of the plugin I have works perfect (0.2)... I basically just need a DOM transform that takes any non oEmbed iframe in my content and wraps it in a <figure class="op-interactive"></figure> tag.

**Comment by nicolinuxfr** [comment]
I have some images inside a div and the plugin doesn't extract the image code. In the Instant Articles, there's nothing. 

Let me know if you need more information !

**Comment by demoive** [comment]
@kkranzo, I just wanted to confirm the question in your penultimate comment that indeed that filter is no longer compatible as of v2 of the plugin.

Fortunately for both you and @nicolinuxfr, the issues you're having should be resolvable by configuring some [Custom Transformer Rules](https://wordpress.org/plugins/fb-instant-articles/faq/). Context:

> The latest version of this plugin makes use of the [Facebook Instant Articles SDK for PHP](https://github.com/facebook/facebook-instant-articles-sdk-php) which contains a Transformer that does all the heavy lifting of converting general markup into valid Instant Articles markup. The way that it knows how to transform source elements into the valid Instant Articles markup is by a set of rules which defines the mapping of how to parse the content of the post/page. Our plugin contains [rules which have been pre-defined](https://github.com/Automattic/facebook-instant-articles-wp/blob/master/rules-configuration.json) to satisfy the most common WordPress source markup. Your source content likely contains elements which are not covered by the packaged ruleset.

Understanding how Transformer Rules work and how to configure them is admittedly complex, which is why we've recently extended our documentation with a section dedicated to help configuring the [Custom Transformer Rules](https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/docs/QuickStart.md#custom-transformer-rules). Hopefully it provides enough information for you to define or make any adjustments necessary to get the transformation to work in your environment.

If you can give that a try, we'll close out this issue in the mean time. And if you find you are unable to define your own custom rules to resolve your scenarios (1) we'd appreciate feedback on what part of the documentation that is lacking and (2) the [community on the WP Forum](https://wordpress.org/support/plugin/fb-instant-articles) can occasionally be quite helpful in providing support.

This issue can be closed for now.

**Comment by nicolinuxfr** [comment]
Indeed, this custom rule made the trick for me : ` { "class": "PassThroughRule", "selector": "div" }`

**Comment by kkranzo** [comment]
Thanks for the writeup @demoive!

I am actually all set with the way I have it setup currently, so I am good to go.
