### ISSUE TITLE
When Instant articles plugin is enabled i get a white screen of death in All plugins page / settings page !

### ISSUE THREAD

**Issue by cusatxpress** [Automattic/facebook-instant-articles-wp#558]
# Steps required to reproduce the problem

1. Activate the plugin from Wordpress plugin directory

# Expected Result

White screen of Death appears. I tried a disabling all plugins and the issue persist.

* Listing of all plugins in Plugins page.
* settings of instant articles page.

# Actual Result

*  I cant take All plugins page.
*  Cant open settings of Instant Articles

# Screenshot

[http://prntscr.com/dhohpw](url)
---

**Version Info**

* Plugin version : Version 3.2.2
* WordPress version:  4.7 i went back in older version but issue persist.
* PHP version: 5.5

**Comment by jordan314** [comment]
+1
500 error Unhandled Exception: "The user must be an administrator of the page in order to impersonate it."

**Comment by cusatxpress** [comment]
I am using the Super Admin account. !

**Comment by everton-rosario** [comment]
@jordan314 @cusatxpress 
Can you double check if you are using VIP or do you have a local installation?

Can you try in the newest [version 3.3](https://github.com/Automattic/facebook-instant-articles-wp/releases/tag/3.3)


Also please provide the stacktrace exception Wordpress throws while accessing the page.

Thanks for using Instant Articles and being helpful by providing us feedback on this.

**Comment by cusatxpress** [comment]
Sure.. i will get back to you after checking Version 3.3 !

**Comment by everton-rosario** [comment]
@cusatxpress Let me know!
Happy new year!

**Comment by cusatxpress** [comment]
Sorry the issue persists on Latest version also.

**Comment by cusatxpress** [comment]
Haai @diegoquinteiro ,
I have the wordpress installed on a shared hosting on HostGator, not VIP nor Local installation.

i checked the error log and found these lines 

```
`Failed opening required '/******/wp-content/plugins/fb-instant-articles/vendor/autoload.php' (include_path='.:/opt/alt/php55/usr/share/pear:/opt/alt/php55/usr/share/php') in /***ml/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php on line 26
[29-Dec-2016 09:23:53 UTC] PHP Warning:  require(/******ml/wp-content/plugins/fb-instant-articles/vendor/autoload.php): failed to open stream: No such file or directory in /*****tml/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php on line 26

[29-Dec-2016 09:26:03 UTC] PHP Fatal error:  require(): Failed opening required '/**************/wp-content/plugins/fb-instant-articles/vendor/autoload.php' (include_path='.:/opt/alt/php55/usr/share/pear:/opt/alt/php55/usr/share/php') in /***tml/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php on line 26

[29-Dec-2016 09:26:11 UTC] PHP Warning:  require(/****ml/wp-content/plugins/fb-instant-articles/vendor/autoload.php): failed to open stream: No such file or directory in /home/cusatrhk/public_html/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php on line 26

[29-Dec-2016 09:26:11 UTC] PHP Warning:  require(/****tml/wp-content/plugins/fb-instant-articles/vendor/autoload.php): failed to open stream: No such file or directory in /****tml/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php on line 26`
```

Please note the version is 3.3

**Comment by cusatxpress** [comment]
Dear @everton-rosario , @diegoquinteiro ,
I updated to latest wordpress update. and turned on WP_DEBUG. 
here i the error with stacktrace exception.

`Fatal error: Uncaught exception 'Facebook\Exceptions\FacebookAuthenticationException' with message 'Error validating access token: The session has been invalidated because the user has changed the password.' in /home/cusatrhk/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Exceptions/FacebookResponseException.php:89 Stack trace: #0 /home/cusatrhk/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create(Object(Facebook\FacebookResponse)) #1 /home/cusatrhk/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(255): Facebook\FacebookResponse->makeException() #2 /home/cusatrhk/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(82): Facebook\FacebookResponse->decodeBody() #3 /home/cusatrhk/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/gra in /home/cusatrhk/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Exceptions/FacebookResponseException.php on line 89`

**Comment by cusatxpress** [comment]
Now i think my issue is #481 , but as my Wordpress Version (4.7) and Instant article Plugin (3.3) are upto date the issue persists.

then i tried #495 , i am able to access the All options Page, i only have these values in the page,
```
instant_articles_fbrlh_state	
instant-articles-option-ads	
instant-articles-option-analytics	
instant-articles-option-fb-app	
instant-articles-option-fb-page	
instant-articles-option-publishing	
instant-articles-option-styles	
instant-articles-wizard-url
```
i changed the values in `instant-articles-option-fb-page` but the issue remains.

**Comment by sahilamanu** [comment]
Even on latest version the issue is there. but i got another way to fix the same. please do note @cusatxpress 

i used the method described by @demoive 


 if you are able to access the "All Settings" page for your WordPress installation there is a workaround:

1. Make sure you have the latest plugin version (currently [**v3.3**](https://github.com/Automattic/facebook-instant-articles-wp/releases/tag/3.3))
2. Navigate to `/wp-admin/options.php` of your installation
3. Clear out the value of the option named `instant-articles-current-state`
if you cant find `instant-articles-current-state` clearing out `instant-articles-option-fb-app` and `instant-articles-option-fb-page` should have the same effect.
4. Click the "Save Changes" button at the bottom.


May be a cache issue with you @cusatxpress , if it doesnt work for you then try the below method.

1. Go to PhpMyadmin.
2. Choose your database.
3. Go to `wp-options` table in your database.
4. Scroll it you find  `instant-articles-option-fb-app` and `instant-articles-option-fb-page`.
5. Clear the value in `instant-articles-option-fb-app` and `instant-articles-option-fb-page` and save.

This will force the plugin to revert to it’s initial state for the Setup Wizard which will avoid the Fatal error you experienced.

6. Now go back to `siteurl/wp-admin/plugins.php` and it will load all the plugins as normal. Attached screenshot : http://prnt.sc/ds6zn1

**This worked for me.** thus closing #558 



and now revalidate again using Facebook to use [**Facebook Instant Articles for WP**](https://github.com/Automattic/facebook-instant-articles-wp/). : http://prntscr.com/ds6zrb

**Comment by mschmo** [comment]
@sahilamanu your `options.php` adjustments fix the white screen of death, however this issue shouldn't just be brushed under the carpet. It really should be handled better and made clear to the user so that they don't have to dig through github issues to find a hacky fix.

Either an alert should be displayed to the user in this case clearly outlining what needs to be done to fix, or a better solution should be implemented. I think this issue should remain open as it is not fixed in the source itself.

**Comment by everton-rosario** [comment]
@sahilamanu @mschmo We did a try/catch to make it an alert and then not letting you fall into this case scenario of having it like this.

In a new installation and never getting the version that previously had the issue, it shouldn't fall into this scenario of white screen/Auth problem.

Can any of you guys replicate this issue even on the newest version (never upgrading, just installing into a vanila WP)?

Thanks for the insights and help thru this.
