### ISSUE TITLE
There is no rule for <hr /> elements

### ISSUE THREAD

**Issue by mrpritchett** [Automattic/facebook-instant-articles-wp#588]
# Steps required to reproduce the problem

1. Create a horizontal rule in WP editor.
2. Check FBIA for hr.
3. None exists.

# Expected Result

* Horizontal rules should show in FBIA's.

# Actual Result

* No `<hr />` tags show

---

**Version Info**

* Plugin version: latest
* WordPress version: 4.7.1
* PHP version: WordPress VIP environment

**Comment by jeremyclarke** [comment]
Looks like this is impossible because there is no "class" in the IA canon for horizontal rule (presumably it would be called HorizontalRuleRule):

https://developers.facebook.com/docs/instant-articles/sdk/transformer-rules

Another tragic failure of the IA API that isn't the fault of this plugin. 

Please correct me if I'm wrong. I was hoping to abuse hr tags to get around the horifically constrained context limitations that block me from having any kind of containers for other tags (hr+stuff+hr to fake a div with a background) but it looks like nope.

**Comment by timjacobi** [comment]
Unfortunately horizontal rules are currently not supported by Instant Articles.

**Comment by timjacobi** [comment]
> @jerclarke @timjacobi
> 
> Should something like this be part of the default ruleset?
> 
> ```
> { "rules": [{"class":"IgnoreRule","selector":"hr"}] }
> ```

cc @diegoquinteiro @Blakomen
