### ISSUE TITLE
Content changes / updates  are not being reflected in Facebook IA after republishing

### ISSUE THREAD

**Issue by Verticalmag** [Automattic/facebook-instant-articles-wp#626]
After original publish of content via WP and article is now in facebook IA lib and being used no further updates seem to be applied.  I'm not able to fine a source of the caching or method to clear.

Simple copy change and republish should be reflected in the IA page.

Suggestions?

**Version Info**

* Plugin version:  Version 3.3.3
* WordPress version: 4.7.2
* PHP version:  7+

**Comment by Nullmegh** [comment]
It does change since the instant article feed changes every time you update a post and facebook too refreshes it every min. You should download the pages manager app and try or perhaps you could clear the facebook app data and try again.

**Comment by timjacobi** [comment]
@Verticalmag is this still an issue? Could you please update to the latest version of the plugin and report if the problem still exists?

**Comment by carlosusa77** [comment]
Hi timjacobi without making any changes I currently have that problem I found a temporary solution but I would like it to work as before, I have only 12 plugins installed on my site and they were
  before installing this instant article and everything worked correctly. I have everything updated to the latest version--- and this was the solution I found

-when you update your post with some other content or some change just copy the url of the post go to https://developers.facebook.com/tools/debug/sharing/ paste the url press debug, after press a liter grey button (extract again) this updates the instantaneous article ,,, as a temporary solution… Excuse my English I'm not very good at writing
If you find the solution to the problem, help me... when I create the post I have to insert it manually because it is not inserted in the instant articles automatic...

**Comment by timjacobi** [comment]
@carlosusa77 Unfortunately automatic import is not supported anymore out of the box. In order to import the article you need to use the sharing debugger as you have described or share the link to the post on Facebook. If you rely on the automatic import please use the RSS feed of this plugin instead. If this still causes problems for you please open a separate issue. I will close this one as the original author hasn't responded in too long.
