### ISSUE TITLE
Page Selection List

### ISSUE THREAD

**Issue by wulbirin** [Automattic/facebook-instant-articles-wp#686]
I have a lot of pages I manage, and I mean **A LOT**, but when I have to integrate IA on them I can't find all the pages in the page selection, there are only a handful pages there. I remove admin status on some pages just to make the others show up but if I do that the plugin disconnects.

The way I see it, there are 2 ways you can solve this problem, either you don't list pages already used for IA.
-or- 
you have some sort of pagination on the page selection list so that all pages can be seen.

I hope you fix this the soonest time possible.
Thank you!

---

**Version Info**

* Plugin version: 3.3.5
* WordPress version: 8.0
* PHP version: 7.0

**Comment by colinhowells** [comment]
if you modify your copy of the plugin's wizard/class-instant-articles-wizard-fb-helper.php
file according to this commit you should be all right:

https://github.com/Automattic/facebook-instant-articles-wp/pull/656

Not sure when pagination will be included in the plugin.

**Comment by wulbirin** [comment]
Thank you so much @colinhowells !
^_^

**Comment by pestevez** [comment]
Hey @wulbirin, thanks for requesting this feature. I don't believe this is a problem anymore since the latest version of the plugin (4.0.5) does not pull the list of pages you manage, and instead, it asks for a Page ID.

I am closing this issue now, but please feel free to reopen if you are still facing this problem or if you need additional information.
