### ISSUE TITLE
404 page not found when i share new articles (after update)

### ISSUE THREAD

**Issue by tavyDesign** [Automattic/facebook-instant-articles-wp#714]
# Steps required to reproduce the problem

1. when i try to share new posts, i get 404 eror from website, in facebook cache
2. all of this is happend after last update and insert that ia_markup
3. 

# Expected Result

* 

# Actual Result

* 

---

**Version Info**

* Plugin version: 4.0.2
* WordPress version: 4.8
* PHP version: 7

**Comment by diegoquinteiro** [comment]
Hi @tavyDesign,

Thanks for reporting. The change that might be causing your issue is that we now trigger a scrape of your article when you save it. If you have a cache or async replication in place in a way that your post is still unavailable to Facebook's scrapper by that time the action `save_post` happens on WordPress, it might scrape a 404 instead.

We'll evaluate the best way to address this use case. Meanwhile you can always manually re-trigger the scrape of the article again after a couple of seconds by using the Share Debugger UI.

**Comment by tavyDesign** [comment]
Is not possible to make it on post publish? After link is available?
