### ISSUE TITLE
instant_articles_content filter not calling my callback

### ISSUE THREAD

**Issue by sgatz** [Automattic/facebook-instant-articles-wp#76]
I'm trying to append text on the end of an instant article content.  The compatibility class for Instant_Articles_Google_Analytics_For_WordPress successfully uses the filter 'instant_articles_content' filter.   

But when I try to add a filter in a MU-plugin, my callback is never called. Am I not calling it correctly or is there a bug here.  

My code below: 
    
    add_filter( 'instant_articles_content', 'lgbtqnation_instant_articles_thirdparty_analytics', 100);

    function lgbtqnation_instant_articles_thirdparty_analytics($content) { 
	$add_text="---example text---";
	$content.=$add_text;
    return $content;
    }

**Comment by TStrothjohann** [comment]
I have got the same issue with this filter.

**Comment by TStrothjohann** [comment]
Hey @sgatz I found out what my mistake was:

*My code:*
`function remove_variants_of_cover_image(){
  return "hello - this is a test!";
}

add_filter( 'instant_articles_content', 'remove_variants_of_cover_image', 10, 1 );`

The filter gets applied when a post is rendered for the feed. This only happens if it has never been done before or if the post has been updated. 

In order to see what this filter is doing, you need to update a post from your feed.

**Comment by mehigh** [comment]
"The filter gets applied when a post is rendered for the feed. This only happens if it has never been done before or if the post has been updated.

In order to see what this filter is doing, you need to update a post from your feed."

This needs to be added to the documentation. I wasted quite some time going back and forth and not understanding why my code I wrote never had any effect...
