### ISSUE TITLE
Ads at the bottom of article not working for me. Please Help!

### ISSUE THREAD

**Issue by marktwatson** [Automattic/facebook-instant-articles-wp#781]
Hi there I have noticed that big publishers like Bored Panda have ads that are not in the content area. They are at the very bottom mixed in with the related articles. They look like Audience Network ads to me. Anyone know what they are and how to add them to the articles?

**Version Info**

* Plugin version: 
* WordPress version: 
* PHP version:

**Comment by bubbleheadinc** [comment]
@markwatson they are Recirculation ads
https://developers.facebook.com/docs/instant-articles/monetization/ad-placement

Scroll down to Placing Ads in Recirculation Units (beta)

**Comment by markwatson** [comment]
@bubbleheadinc I think you meant to mention @marktwatson :stuck_out_tongue_winking_eye:

**Comment by pestevez** [comment]
@marktwatson, in addition to the link shared before, you can also find a related press release here: https://media.fb.com/2017/11/06/instant-articles-introduces-monetization-tab-with-simpler-one-click-control-for-turning-on-recirculation-ads/

I am closing this issue since your original request was to get information about these type of ads, and there is a global option to enable them in all Instant Articles; but please let me know if you need additional information.
