### ISSUE TITLE
Subdomain posts weren't published as Instant Articles

### ISSUE THREAD

**Issue by zomidaily** [Automattic/facebook-instant-articles-wp#805]
My main site www.example.com has no problem. I create separate database for subdomain as video.example.com, and I didn't notice any problem the first few weeks. But recently, the posts from my subdomain video.example.com weren't publish as Instant Articles.

## Expected Result
I thought if I registered the Root Domain example.com/, the subdomain will be published as Instant Articles according to this https://developers.facebook.com/docs/instant-articles/guides/publishertools/

In the "Production RSS Feed" field, I had set up "https://www.example.com/feed/instant-articles". 

I tested "https://www.video.example.com/feed/instant-article" in the "Production RSS Feed", and then the subdomain posts are imported to Instant Articles. But the problem is I can't enter two feed urls in the "Production RSS Feed".

How can I solve this problem? Is it possible to merge multiple urls in the "Production RSS Feed"?

## Version Info
* Plugin version: 4.0.5
* WordPress version: 4.8.3
* PHP version: 7.1

![screenshot_1](https://user-images.githubusercontent.com/4189681/32552409-d3be1aa4-c4ce-11e7-83dd-548dffb5a8cb.jpg)

**Comment by pestevez** [comment]
Hey @zomidaily,

You are right about registering the root domain, it means you have also registered your subdomains.

I am not sure how the description of your issue relates to the Instant Articles WordPress plugin because if you use the plugin you don't need to use the RSS feed. Can you please clarify?

In any case, you won't be able to configure multiple RSS feeds for Instant Articles on Facebook, so if you will have to generate a single RSS feed containing all articles from your multiple subdomains.

**Comment by pestevez** [comment]
I am closing the issue now due to inactivity. Please feel free to reopen if you need additional information.

**Comment by zomidaily** [comment]
Hi @pestevez 

My subdomain posts weren't import to Instant Article again (it looks on and off). I provide the Markup here, and I hope you can check for me what could be the problem. Regards,

Source Markup
https://gist.github.com/zomidaily/244b91d298cd1d17e1bf3562b9b83020

Transformed Markup
https://gist.github.com/zomidaily/bf0d8dc0a7274710b6148990d531c8b1

**Comment by pestevez** [comment]
Hey @zomidaily - I was able to see the Instant Article for the URL provided in your markup, but I had to re-scrape your page using the [Sharing Debugger](https://developers.facebook.com/tools/debug/sharing/). I believe the behavior you describe of Articles being imported sometimes is because the plugin is not creating them as soon as you create your post, but the first time the Facebook Crawler scrapes them.

In summary, your Instant Articles markup is being created correctly, even if you don't see the Instant Article under Publishing Tools. Once the Article URL is shared on Facebook, the crawler will create the Instant Article. If you want to see the article under Publishing Tools before the article URL is shared on Facebook, you can trigger a manual scrape using the Sharing Debugger.

I will leave the issue open, in case you need additional information.

**Comment by zomidaily** [comment]
Hi @pestevez 
There is no problem with my main domain as new posts are imported into "Production Articles" almost immediately. The problem is only on my subdomain, but at least I can use the "Sharing Debugger" tool and it is imported to "Production Articles" manually now.

And I just curious that why some posts are shown as "RSS Feed" while the others don't? See the attached photo. 
![rss](https://user-images.githubusercontent.com/4189681/32697751-966f87bc-c7d2-11e7-845e-deb368311998.jpg)

**Comment by diegoquinteiro** [comment]
Hi @zomidaily!

Since v4, all your articles should be imported by the Facebook Crawler **at the time they are shared** on Facebook as long as you correctly set the proper Page ID on the plugin settings screen. You don't need to manually trigger the ingestion by using the Share Debugger for every article, because the ingestion will happen once you or some of your readers share the article on Facebook. The Share Debugger will be useful if you want to see/debug your article before posting on Facebook.

It seems like you still have RSS enabled. On this configuration Facebook will import the articles by using the 2 methods at the same time, which leads to some of them to go through by RSS and some by the regular Crawler ingestion. If you are on v4+ you can disable the RSS on Facebook - this feed is only kept on the plugin for backwards compatibility.

Thanks!
