### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nittypr007** [Automattic/facebook-instant-articles-wp#807]
## Steps required to reproduce the problem

1. 
![capture](https://user-images.githubusercontent.com/28990513/32588000-2a3ece54-c50c-11e7-8b26-499e47833c38.JPG)
![qqwqw](https://user-images.githubusercontent.com/28990513/32588001-2e509cb6-c50c-11e7-9df2-386621ac641f.JPG)

2 . www.womengcars.club
3.  Can someone help me PLS

## Actual Result 
If your issue is about the error message _No rules defined for ..._. Please do the following.
* Go to the Wordpress editor and open the post
* In the Instant Article plugin section click on _[Toggle debug information]_
* Share both _Source Markup_ and _Transformed Markup_

## Version Info

Please state _exact_ versions, not _latest_ or _new_.

* Plugin version:   4.0.5
* WordPress version: 4.8.3
* PHP version: 5.6.32

Without the above information we are not able to debug the issue and will close it.

**Comment by nittypr007** [comment]
can someone help me what i need to do so this can be fixet my mobile page is good

**Comment by pestevez** [comment]
Hey @nittypr007,

I don't think this is related to the plugin (since the screenshot shows a 404), but this is my recommendation:

1. Disable Development Mode in your plugin settings
2. Choose 10 of your posts and Update them (to ensure they are saved with the development mode disabled.)
3. Trigger a manual rescrape for all those 10 posts using the [Sharing Debugger](https://developers.facebook.com/tools/debug/sharing/). (Pass the URL of the 10 articles you chose)
4. Request a new review of your content.

I will proceed to close this issue since it is not related to the plugin itself. If after the review process is completed you are still having problems, please feel free to reopen BUT include the information requested for our team to be able to troubleshoot i.e Source Markup and Transformed Markup. Thanks!
