### ISSUE TITLE
http:// to https:// migration, all previsouly published articles are offline?

### ISSUE THREAD

**Issue by DrLightman** [Automattic/facebook-instant-articles-wp#849]
## Steps required to reproduce the problem

1. have an http (not SSL) website: http://example.org
2. publish many many many articles on Facebook Instant Library successfully, and you're happy
3. one day, decide to switch to SSL: https://example.org. do it in the right way, all redirects in place to redirect 301 whole website content from http to https
4. suddendly realize that all previously submitted articles on library are broken, they don't show on facebook instant articles app, maybe because internally they link the old canonical http version of the article: `<link rel="canonical" href="http://example.org/some-article/"/>`

<img src="https://i.imgur.com/am5AOCG.png" />

## Expected Result

I would expect that protocol really wouldn't matter on a previsouly submitted article and that with a migation from http to https, or viceversa, articles would continue to show up on Facebook IA app.

## Actual Result 

Corresponding instant articles for the https migrated https://example.org/some-article/ is not found even if exists in library from when hte protocl was http.

## Version Info

* Plugin version: 4.0.6
* WordPress version: 4.6.9
* PHP version: 5.6.32

## My thoughts on possibile solutions:

If I'm not wrong, unfortuntaley latest version of the plugin inhibits the direct submission into ia library. Otherwise I would do as I did in the past, a command line php script to cycle through the whole blog's post to trigger an update on every one of them to trigger/renew a submission into IA library. It worked in the past, I'm asking here if it would work again.

I tried to edit the link canonical by hand in the library but this message pop up:

<img src="https://i.imgur.com/spz4IbW.png" />

Please suggest any solution, I think this is a serious flow on how published articles are handled since someone here worked hard to implement SSL as widely suggested everywhere as a good practice to deliver web pages and now after doing that all the past work of months of published articles has been reset in a click.

Thank you very much for the attention.

**Comment by pestevez** [comment]
Hey @DrLightman,

A few comments:
- The Instant Articles spec includes the URL protocol as part of the canonical URL.
- The canonical URL is the ID of the Instant Article, so it cannot be changed for a given Instant Article.
  - If you edit the markup and edit the canonical URL, as in your example, what will happen is that a new Instant Article will be created, with the canonical URL having `https`.

Can you check what happens if you trigger a re-scrape using the [Sharing Debugger](https://developers.facebook.com/tools/debug/sharing/) on any of your URLs using `https`? I believe it would pick the markup pointing the canonical URL with `https` and create the new Instant Article you are looking for. If it works, you could write a script that triggers re-scrapes then.

In any case, we should explore a simpler way for the plugin to handle situations like your, where a whole site is configured to redirect.

Let me know if this helps.

**Comment by DrLightman** [comment]
Hi @pestevez , thank you for the getting back to me so fast.

I have confirmed your points, editing the canonical from inside the library will create an unpublished copy of the old http version. For a bunch of articles it would be fasible but we've got around 300'000 so I'm obligated to batch/automate the process.

I've seen in the debugger and forcing a rescrape does the trick too. My problem now is if I use some internal plugin function to issue the rescrape in my command line's script loop or I have to write one myself. I've found this information that says I need a POST request plus an access token to issue a rescrape since 16 Oct, 2017:

https://developers.facebook.com/blog/post/2017/07/18/graph-api-v2.10/

> When making a GET request against a URL we haven't scraped before, we will also omit the og_object field. To trigger a scrape and populate the og_object, issue a POST /{url}?scrape=true. Once scraped, the og_object will remain cached and returned on all future read requests.

Do you by any chance have in mind the the plugin contains maybe an hidden or helper function to do this request?

Thank you!

**Comment by pestevez** [comment]
I am glad it helped. I agree, for that many posts a manual process is not feasible.

If you have a way to get all the posts URLs, you can trigger a re-scrape (as the article you found explains) with `POST /?id={URL}&scrape=true`, but you will need to use an access token for the request (more details here: https://developers.facebook.com/docs/sharing/opengraph/using-objects#update)

In the past, we used to store access token in the plugin, but it caused confusion for some users because of its complexity. We are currently discussing if we should bring that feature back (perhaps as an advanced optional setting) to allow triggering a re-scrape directly from the plugin.

**Comment by DrLightman** [comment]
Okay I think I managed, the script is running, 1 second of wait between requests, I'm hoping not getting banned. I hope the FacebookApp AccessToken won't expire either.
Thanks for the support.

**Comment by everton-rosario** [comment]
Thanks for reporting @DrLightman , but the process of rescraping and updating the content like this is the proper way of managing this kind of migration.
Creating some sort of migration on our side doing it blindly for all the URLs might not be the best solution looking from full community perspective.
We rather have a way that convers all cases, like the one @pestevez mentioned than implementing something more restrictive that will help only few from community.

Thanks for reporting it and using the plugin.
