### ISSUE TITLE
Plugin was not activated - Fatal Error

### ISSUE THREAD

**Issue by cusatxpress** [Automattic/facebook-instant-articles-wp#86]
When I tried activating the plugin it says Fatal error and returns this message :+1: 

> Warning: require(PATH/wp-content/plugins/facebook-instant-articles-wp-master/vendor/autoload.php): failed to open stream: No such file or directory in PATH/wp-content/plugins/facebook-instant-articles-wp-master/facebook-instant-articles.php on line 15

> Fatal error: require(): Failed opening required 'PATH/wp-content/plugins/facebook-instant-articles-wp-master/vendor/autoload.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in PATH/wp-content/plugins/facebook-instant-articles-wp-master/facebook-instant-articles.php on line 15.

Please help me !

**Comment by diegoquinteiro** [comment]
Hi, Diego from Facebook here.

This new version of the plugin now uses composer for package management. I'll open a PR to update the readme.txt to reflect this ASAP.

Please install composer: https://github.com/composer/composer

And do a `composer install` on the root directory of the plugin.

**Comment by YOzaz** [comment]
Suggestion to fix composer.json and publish it to Packagist.org.

**Comment by donaldG** [comment]
So, a question: is this plugin intended to be a starting off point for developers to just modify as needed? I assume not? Also, forgive me, this is my first time with Composer and I was able to install it and get it running easily but that seems like a sort of big step for folks who just want to turn this on and let it roll. It also seems like an odd thing for a WP plugin to have so I suppose my question is: Is there a way in the future that all of dependencies will be bundled into the plugin without the need for Composer? I sort of assume the answer is "Yes" but I hate to assume. I also sincerely appreciate all the work on this!!

**Comment by YOzaz** [comment]
@donaldG composer is becoming a mandatory knowledge for all SDKs :) and it's easy to use!

**Comment by tjm71** [comment]
I get the same error. Shouldn't the plugin work out of the box?

**Comment by donaldG** [comment]
Sure, and I agree it was easy it just seems extra-ordinary for a WP plugin
where there will certainly be very basic users wanting to implement this &
I'd suspect the knowledge of running Composer may be a bit much. I guess
I'm just trying to understand the true purpose of this plugin, is it a
building block for developers to fully customize as needed? Or should it be
treated like a regular WP plugin. At the moment it seems to be sraddling
the line, IMO.

**Comment by YOzaz** [comment]
Well, if that'd be a regular WordPress plugin - it would sit in WordPress plugins repository.
But it's not - and until WordPress plugins system will upgrade itself to support current open-source standards, we have to deal with additional steps.

**Comment by diegoquinteiro** [comment]
@YOzaz should/can we append a bundled version of the plugin to the release (including the vendor folder)?

**Comment by YOzaz** [comment]
@diegoquinteiro I can't answer that directly - it depends.
Ideally, as WordPress natively doesn't support plugin post-install commands (or does it?), I would take such approach:

* For advanced developers, I would leave it on GitHub with install instructions - maybe even make this package available through Packagist (but you'll need to solve default paths composer creates).
* For general users, I would create an automated build scripts, which would install all dependencies and prepare one ZIP / TAR.GZ file, production ready, which needs only extraction. This build can be triggered for every release as Github hook.

Latter option will allow you to submit plugin to WordPress plugin directory as well.
Automation can be done using Node.js or native bash commands through build script.

**Comment by YOzaz** [comment]
While I'm thinking it further - lots of WordPress installations are on shared hosting, which - usually - doesn't have SSH access, therefore can't install and run composer. So, production-ready build is kind of "a must".

**Comment by donaldG** [comment]
@YOzaz I was traveling and emailing my response but now that I'm back in front of my computer I figured I'd chime in again ;) It looks like a version of the plugin IS already in the main WP plugin repo: https://wordpress.org/plugins/fb-instant-articles/

To my knowledge there aren't really post-install commands for WP plugins. There may be settings to config, or something of that nature but typically there's nothing else that needs to be done. Generally it seems all of the dev stuff is written into the program via hooks/filters/functions and everything else would work pretty out of the box for a standard user.

I certainly recognize this is a unique plugin but it seems it would be deviating from the WP standard to maintain two separate versions: a dev version on Github & a regular version on WP Plugin repo. It's not uncommon for a WP plugin to have both a Git location & WP location but they're typically the same. Sometimes, I suppose, if a user doesn't want to submit to WP they can just leave the plugin on WP but especially since this is Automattic/Dekode/Facebook I would assume the finished version of this plugin would sit in the WP repo (I say "finished" because Instant Articles isn't accessible to everyone until the 12th so this is sort of technically still in development I believe?)

I suppose all of that more adequately addresses my concern with Composer.

**Comment by YOzaz** [comment]
@donaldG you're basically right. Actually, on smaller hosting instances like Amazon AWS users may not even have enough memory to run `composer install`, even if they'll get SSH access.
There's a workaround though - you can remove `vendor` directory from `.gitignore` file and commit dependencies as well - this will make package complete, and still updateable through composer. Just remember to add `vendor/.git` to `.gitignore`, otherwise people will run into issues.
This article is somewhat related and explains necessity to ignore git config files: http://www.lornajane.net/posts/2014/using-composer-without-gitignoring

**Comment by YOzaz** [comment]
Oh by the way @donaldG - we're being pushed by Media Support to launch Instant Articles, as we've got exclusive access. I believe lots of big publishers got this as well.
And of course, we want to use new plugin version so we don't have to do installing / testing / enabling process again :smile: Do you have any idea / insight when the PRs will be merged?

**Comment by donaldG** [comment]
@YOzaz re: "any idea/insight when the PRs will be merged" I don't :( I'm just a lowly developer trying to use this for our organization and got a tight deadline handed down from our marketing team, ha. I wish that I had exclusive access to the FB side of this so I could see exactly how it's all going to work but it looks like I'll just be in a panicked frenzy tomorrow trying to integrate all of this. Thank you for that article on the vendor/gitignore side of it though!!

**Comment by YOzaz** [comment]
@diegoquinteiro - you do have some insights, don't you? :smile:

**Comment by donaldG** [comment]
@YOzaz @diegoquinteiro looks like this is basically the same as #94, yeah? And so now there's version 2.3 in the WP repo, woooooo! https://wordpress.org/plugins/fb-instant-articles/

**Comment by YOzaz** [comment]
@donaldG yep, it's solved now.

**Comment by diegoquinteiro** [comment]
Thank you all =)

**Comment by cusatxpress** [comment]
Thank you all :) for the replies... :)

*Regards, *




First in CUSAT to go Social


*----------------------------------------------------------------*
<https://www.facebook.com/CusatXpress>
<https://www.twitter.com/cusatianxpress>
<https://plus.google.com/116788670407330871558>
<http://www.linkedin.com/profile/view?id=196278519>
<http://www.youtube.com/user/CusatXpress> <cusatxpress@gmail.com>
-------------------------------------------------------------------------------
