### ISSUE TITLE
Future image not showing for my Facebook Instant Articles 

### ISSUE THREAD

**Issue by VanasriJithendar** [Automattic/facebook-instant-articles-wp#886]
Future image not showing on my Facebook Instant Articles when I add youtube video in the article. Please check the attached screenshot for reference.

I have enabled Use video in News Feed link preview when available later I disabled it. But the problem is still annoying. Please give me a suggestion.

![screenshot_20180226-223113](https://user-images.githubusercontent.com/20453233/36841677-0dd20fea-1d6f-11e8-9e1f-b5aeff5468d6.png)

**Comment by vkama** [comment]
Are you following these guidelines here:
https://developers.facebook.com/docs/instant-articles/design/videolink
I think Youtube embeds are not supported, you have to link to the actual video file for it to work.

**Comment by VanasriJithendar** [comment]
Yes. I have disabled Use video in News Feed link preview. But still getting problem.

**Comment by codeslane** [comment]
@VanasriJithendar, Can I see the list of plugins you're currently using. Also, Double check that you have set the featured image or not. 

Also, have you tried facebook debugger to get the status of your OG. 
If not, try debugging your URL here: https://developers.facebook.com/tools/debug/

Let me know if this works.

**Comment by codeslane** [comment]
@VanasriJithendar, As I can check & found that the image is fetching properly. But, the issue is that your featured image size isn't perfect/ up to the mark. Please check the size.

<img width="524" alt="debugger1" src="https://user-images.githubusercontent.com/26877201/36908242-b789aa6a-1e60-11e8-80f9-060e067be702.png">
<img width="1068" alt="debugger" src="https://user-images.githubusercontent.com/26877201/36908243-b7e29c9c-1e60-11e8-9ba6-f91caebeda90.png">

Try uploading a new featured image.
Recommended Size: 1200 * 780 

Thanks
Vaibhav

**Comment by VanasriJithendar** [comment]
@codeslane I have updated with 1200 * 780 size image but same problem..

**Comment by VanasriJithendar** [comment]
I think the problem is with og:type. Can any one tell me that how to change og:type video.other to article.
