### ISSUE TITLE
INSTANT ARTICLE 

### ISSUE THREAD

**Issue by keralafbmedia** [Automattic/facebook-instant-articles-wp#974]
HI,
i cant connect my website with instant article.. i got a notification in Facebook like ( You've Lost Access to Instant Articles Your articles either have minimal readership or are not currently meeting the content policies for Instant Articles. To reapply for access, submit for review when you have at least 10 articles in your production library and have increased your traffic. ) like this 

actually i am following all the terms and conditions

**Comment by jerclarke** [comment]
You don't decide if you are meeting the ToS, Facebook does, and they don't tell you what part you are in violation of. 

Importantly, the "minimal readership" part of it is completely subjective to them and can change any time they want (months ago most sites got ejected because you needed thousands/tens-of-thousands of traffic all of a sudden, when previously there was no minimum).

Facebook doesn't care about you or whether you understand why you are in violation of the rules. You can re-apply but basically it is a slot machine. 

Good luck. I advise you to make sure you have a good fast mobile version that doesn't rely on Facebook.

**Comment by BrookeDot** [comment]
I'm going to go ahead and close this as it is not regarding a problem itself rather an administrative concern. 

Facebook's current Instant Articles Policies can be found using the following link:
https://developers.facebook.com/docs/instant-articles/policy

That link also contains information on getting support directly from Facebook.
